### PR TITLE
Add option for proxy reset

### PR DESCRIPTION
**Pull request by themousepotato**
Using the same script set_proxy.sh the user can reset the proxy as well. It can be done by using --reset option in the command line. #3 done.

### CODE REVIEW

**Comment by thealphadollar** [comment]
Kudos @TheMousePotato, but I'm skeptical about truncating the files; they store other useful information too. Eg. allowing unauthenticated repos.

I would suggest finding a way to get the line number and delete that particular line. 

You can use regex to find the pattern of line to delete in a file and then the `sed` command :dancer:

**Comment by thealphadollar** [comment]
@TheMousePotato Ping.

**Comment by themousepotato** [comment]
Hey @thealphadollar!

I'll be working on this from now.

**Comment by thealphadollar** [comment]
Thanks for the contribution, @TheMousePotato  :fireworks:

**Pull request merged**
