### PR TITLE
Update set_proxy.sh

### PR DESCRIPTION
**Pull request by baymac**
Added arguments for hostname and port. Refractored code into functions.

I have added arguments in the script so that user enters the hostname and port while executing the command. I used _shift_ command to shift through the arguments. The following is the part of code which I have added:

`if [ "$#" -eq 4 ]; then
  while [ "$1" != "" ]; do
    case $1 in
      -h| --host)
        shift
        PROXY_HOST=$1
        echo $PROXY_HOST
        shift
        case $1 in
          -p| --port)
            shift
            PROXY_PORT=$1
            echo $PROXY_PORT
            shift
            ;;
          *) 
            exit_with_usage 
            ;;
        esac
        ;;
      *) 
        exit_with_usage 
        ;;
    esac
  done
  else
    exit_with_usage
fi`

You can execute the script by `sudo ./set_proxy.sh -h [host ip] -p [port no.]`

In rest of the code I have done modifications only. Refactored the code into functions such as enviroment_set_proxy, exit_with_usage, reset_proxy etc.

### CODE REVIEW

**Review by thealphadollar — CHANGES_REQUESTED** [review]
Great work there; I would like to know if you still ask for missing arguments because I wasn't able to figure out.

If not, then you should add the option to ask for the argument if not given.

**Comment by baymac** [comment]
Hey @thealphadollar , when user doesn't enter the argument or enters wrong argument then the script exits with instructions about usage of the command as shown in this [image](https://i.imgur.com/vaypyRS.png). Generally all the scripts follow this paradigm and adding multiple options would only make the code longer and difficult to read. Let me know what you think.

**Review by thealphadollar — APPROVED** [review]

**Comment by thealphadollar** [comment]
LGTM!

Thank you for the PR.

**Comment by thealphadollar** [comment]
Always send PR after creating a new branch @baymac

**Comment by baymac** [comment]
@thealphadollar I created a fork, made a branch then made a pull request. Are you suggesting that I should create a branch in this repository itself?

**Comment by thealphadollar** [comment]
No, create a branch in your fork itself.


*Shivam Kumar Jha*

*Department Of Computer Science And Engineering*
*Indian Institute of Technology Kharagpur*

*Web <https://thealphadollar.github.io> || Github
<https://github.com/thealphadollar/> || LinkedIn
<https://www.linkedin.com/in/thealphadollar/>
<https://thealphadollar.github.io/>*

**Comment by baymac** [comment]
I did the same, it was named baymac-optimisation-1. Although I merged it with my master soon after. Maybe that is the issue you are talking about?

**Comment by thealphadollar** [comment]
Yes, do not merge it. Send PR from the branch itself.

**Pull request merged**
